# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
        
    - name: Install and Build 🔧
      run: |
        yarn install
        yarn build
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.

